FROM jupyter/base-notebook:latest

# Python dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir build
COPY ./requirements.notebook .
RUN pip install --no-cache-dir -r requirements.notebook

# disable security (this is intended for local use)
RUN echo "c.NotebookApp.token = ''" >> /etc/jupyter/jupyter_notebook_config.py

# access project (shared volume)
WORKDIR /notebook

# expose & launch
EXPOSE 8888
CMD ["start-notebook.sh"]