FROM python:3.12-slim

RUN pip install --upgrade pip==25.3.0

# Python dependencies
COPY ./requirements.notebook .
RUN pip install --no-cache-dir -r requirements.notebook

COPY ./agent /agent
RUN pip install --no-cache-dir /agent

# access project (shared volume)
WORKDIR /notebook

# expose & launch
EXPOSE 8888
CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--ServerApp.token=", "--ServerApp.password="]