FROM python:3.12-slim

RUN pip install --upgrade pip==25.3.0

WORKDIR /app
COPY ./encoding /app/encoding

RUN pip install --no-cache-dir /app/encoding

EXPOSE 6999
CMD ["python", "-m", "encoding", "0.0.0.0", "6999"]