FROM nvidia/cuda:13.0.1-devel-ubuntu24.04

RUN apt-get update && apt-get install -y \
    python3.12 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN rm -f /usr/lib/python*/EXTERNALLY-MANAGED

RUN pip3 install vllm==0.13.0

WORKDIR /app
COPY ./inference /app/inference
RUN pip3 install --no-cache-dir /app/inference

EXPOSE 6999
CMD ["python3", "-m", "inference", "0.0.0.0", "6999"]