FROM vllm/vllm-openai:v0.13.0

RUN pip install --upgrade pip==25.3.0

WORKDIR /app
COPY ./inference /app/inference

RUN pip install --no-cache-dir /app/inference

EXPOSE 6999
CMD ["python", "-m", "inference", "0.0.0.0", "6999"]